from decimal import Decimal

from app.domain.enums import OutputSemantics
from app.providers.base import ModelCapabilities


MODEL_CAPABILITIES = (
    ModelCapabilities(
        provider="volcengine",
        model="doubao-seedream-5-0-lite-260128",
        display_name="Seedream 5.0 Lite",
        supports_text_to_image=True,
        supports_image_edit=True,
        min_outputs=1,
        max_text_outputs=15,
        max_edit_outputs=14,
        default_size="2048x2048",
        single_output_semantics=OutputSemantics.FIXED,
        multiple_output_semantics=OutputSemantics.MAXIMUM,
        unit_price_cny=Decimal("0.22"),
        price_checked_on="2026-07-21",
        documentation_url="https://www.volcengine.com/docs/82379/1541523",
    ),
    ModelCapabilities(
        provider="volcengine",
        model="doubao-seedream-4-5-251128",
        display_name="Seedream 4.5",
        supports_text_to_image=True,
        supports_image_edit=True,
        min_outputs=1,
        max_text_outputs=15,
        max_edit_outputs=14,
        default_size="2048x1536",
        single_output_semantics=OutputSemantics.FIXED,
        multiple_output_semantics=OutputSemantics.MAXIMUM,
        unit_price_cny=Decimal("0.25"),
        price_checked_on="2026-07-21",
        documentation_url="https://www.volcengine.com/docs/82379/1541523",
    ),
    ModelCapabilities(
        provider="volcengine",
        model="doubao-seedream-4-0-250828",
        display_name="Seedream 4.0",
        supports_text_to_image=True,
        supports_image_edit=True,
        min_outputs=1,
        max_text_outputs=15,
        max_edit_outputs=14,
        default_size="2048x1536",
        single_output_semantics=OutputSemantics.FIXED,
        multiple_output_semantics=OutputSemantics.MAXIMUM,
        unit_price_cny=Decimal("0.20"),
        price_checked_on="2026-07-21",
        documentation_url="https://www.volcengine.com/docs/82379/1541523",
    ),
    ModelCapabilities(
        provider="alibaba",
        model="qwen-image-2.0",
        display_name="Qwen-Image 2.0",
        supports_text_to_image=True,
        supports_image_edit=True,
        min_outputs=1,
        max_text_outputs=6,
        max_edit_outputs=6,
        default_size="2368*1728",
        single_output_semantics=OutputSemantics.FIXED,
        multiple_output_semantics=OutputSemantics.EXACT,
        unit_price_cny=Decimal("0.20"),
        price_checked_on="2026-07-21",
        documentation_url="https://help.aliyun.com/zh/model-studio/qwen-image-api",
    ),
    ModelCapabilities(
        provider="alibaba",
        model="qwen-image-2.0-pro",
        display_name="Qwen-Image 2.0 Pro",
        supports_text_to_image=True,
        supports_image_edit=True,
        min_outputs=1,
        max_text_outputs=6,
        max_edit_outputs=6,
        default_size="2368*1728",
        single_output_semantics=OutputSemantics.FIXED,
        multiple_output_semantics=OutputSemantics.EXACT,
        unit_price_cny=Decimal("0.50"),
        price_checked_on="2026-07-21",
        documentation_url="https://help.aliyun.com/zh/model-studio/qwen-image-api",
    ),
    ModelCapabilities(
        provider="alibaba",
        model="wan2.7-image",
        display_name="Wan2.7 Image",
        supports_text_to_image=True,
        supports_image_edit=True,
        min_outputs=1,
        max_text_outputs=4,
        max_edit_outputs=4,
        default_size="2048*1536",
        single_output_semantics=OutputSemantics.FIXED,
        multiple_output_semantics=OutputSemantics.EXACT,
        unit_price_cny=Decimal("0.20"),
        price_checked_on="2026-07-21",
        documentation_url="https://help.aliyun.com/zh/model-studio/wan-image-generation-and-editing-api-reference",
    ),
    ModelCapabilities(
        provider="alibaba",
        model="wan2.7-image-pro",
        display_name="Wan2.7 Image Pro",
        supports_text_to_image=True,
        supports_image_edit=True,
        min_outputs=1,
        max_text_outputs=4,
        max_edit_outputs=4,
        default_size="2048*1536",
        single_output_semantics=OutputSemantics.FIXED,
        multiple_output_semantics=OutputSemantics.EXACT,
        unit_price_cny=Decimal("0.50"),
        price_checked_on="2026-07-21",
        documentation_url="https://help.aliyun.com/zh/model-studio/wan-image-generation-and-editing-api-reference",
    ),
)
